### ISSUE TITLE
数据量多时，节点展开动画有一点卡顿

### ISSUE THREAD

**Issue by anrananran** [TinyWisp/twtree#38]
有没有办法可以丝滑一点？

**Comment by TinyWisp** [comment]
你好，加上animationDuration="0"禁用动画试试。

请问下，你那边数据量多大，一棵树多少个节点，能否发代码看看？

**Comment by anrananran** [comment]
数据量其实也不算大，也就90来个节点，代码很常规。就是展开的时候节点会先叠在一起，然后才展开，看起来很奇怪。

data中的定义：
`
tree: {
    data: [],
    animationDuration: '0.25s',
    defaultAttrs: {
      style: {
        extraAlwaysVisible: true,
        extraFloatRight: false
      }
    }
  }
`

数据获取：
`
const treeData = res.data ?? []
this.tree.data = flat2Nest(treeData, { id: 'menuId', pid: 'parentId', children: 'children' }, (node) => {
  node.id = node.menuId
  node.title = isEmpty(node.subMenuName) ? node.menuName : node.subMenuName
  node.hasChild = node.children?.length > 0
  node.directoryState = node._level === 0 ? 'expanded' : 'collapsed'
  node.menuStatus = node.status
  node.checkbox = {
    show: true,
    disable: false,
    state: !isEmpty(node.subMenuId) ? 'checked' : 'unchecked'
  }
})
`

模板代码：
`
<Twtree
    v-if="tree.data.length > 0"
    ref="refTree"
    :tree="tree.data"
    :default-attrs="tree.defaultAttrs"
    :animation-duration="tree.animationDuration"
    :fn-before-drag="() => false"
  >
    <template slot="icon">
      <ph-icon name="user-list" size="20px" />
    </template>
    <template slot="extra" slot-scope="{ node }">
      <el-button v-show="showEdit(node)" type="warning" icon="el-icon-edit" title="编辑" @click="editNode(node)" />
    </template>
  </Twtree>
`

**Comment by anrananran** [comment]
![image](https://github.com/TinyWisp/twtree/assets/12759613/680f458b-cbed-4f40-9957-30fc7c956a8c)

**Comment by TinyWisp** [comment]
源码中，动画是CSS做的，代码如下：
```css
.twtree-node-enter-to, .twtree-node-leave {
  height: var(--height);
  opacity: 1;
}
.twtree-node-enter, .twtree-node-leave-to {
  height: 0;
  opacity: 0;
}
.twtree-node-enter-active, .twtree-node-leave-active {
  transition: height var(--animationDuration), opacity var(--animationDuration);
}
```
因此，只要覆盖这些CSS样式，就能改变动画效果。

**解决方案：**
使节点高度不是从0开始，这样能减少那种重叠，重影的感觉。
在你的代码中加上如下代码试试：
```css
<style scoped>
::v-deep .twtree-node-enter, .twtree-node-leave-to {
  height: 5px;
  opacity: 0;
}
</style>
```
